package top.srcres258.skyresources.datagen

import net.minecraft.data.PackOutput
import net.neoforged.neoforge.client.model.generators.ItemModelProvider
import net.neoforged.neoforge.common.data.ExistingFileHelper
import top.srcres258.skyresources.SkyResources
import top.srcres258.skyresources.item.ModItems

class ModItemModelProvider(
    output: PackOutput,
    existingFileHelper: ExistingFileHelper
) : ItemModelProvider(output, SkyResources.MOD_ID, existingFileHelper) {
    override fun registerModels() {
        basicItem(ModItems.PLANT_MATTER.get())
        basicItem(ModItems.ENRICHED_BONE_MEAL.get())
        basicItem(ModItems.HEAVY_SNOWBALL.get())
        basicItem(ModItems.EXPLOSIVE_HEAVY_SNOWBALL.get())

        basicItem(ModItems.WOODEN_HEAT_COMPONENT.get())
        basicItem(ModItems.STONE_HEAT_COMPONENT.get())
        basicItem(ModItems.BRONZE_HEAT_COMPONENT.get())
        basicItem(ModItems.IRON_HEAT_COMPONENT.get())
        basicItem(ModItems.STEEL_HEAT_COMPONENT.get())
        basicItem(ModItems.ELECTRUM_HEAT_COMPONENT.get())
        basicItem(ModItems.NETHER_BRICK_HEAT_COMPONENT.get())
        basicItem(ModItems.LEAD_HEAT_COMPONENT.get())
        basicItem(ModItems.MANYULLYN_HEAT_COMPONENT.get())
        basicItem(ModItems.SIGNALUM_HEAT_COMPONENT.get())
        basicItem(ModItems.END_STONE_HEAT_COMPONENT.get())
        basicItem(ModItems.ENDERIUM_HEAT_COMPONENT.get())
        basicItem(ModItems.DARK_MATTER_HEAT_COMPONENT.get())
        basicItem(ModItems.LIGHT_MATTER_HEAT_COMPONENT.get())
        basicItem(ModItems.OSMIUM_HEAT_COMPONENT.get())
        basicItem(ModItems.REFINED_OBSIDIAN_HEAT_COMPONENT.get())

        basicItem(ModItems.WOODEN_ALCHEMY_COMPONENT.get())
        basicItem(ModItems.STONE_ALCHEMY_COMPONENT.get())
        basicItem(ModItems.BRONZE_ALCHEMY_COMPONENT.get())
        basicItem(ModItems.IRON_ALCHEMY_COMPONENT.get())
        basicItem(ModItems.STEEL_ALCHEMY_COMPONENT.get())
        basicItem(ModItems.ELECTRUM_ALCHEMY_COMPONENT.get())
        basicItem(ModItems.NETHER_BRICK_ALCHEMY_COMPONENT.get())
        basicItem(ModItems.LEAD_ALCHEMY_COMPONENT.get())
        basicItem(ModItems.MANYULLYN_ALCHEMY_COMPONENT.get())
        basicItem(ModItems.SIGNALUM_ALCHEMY_COMPONENT.get())
        basicItem(ModItems.END_STONE_ALCHEMY_COMPONENT.get())
        basicItem(ModItems.ENDERIUM_ALCHEMY_COMPONENT.get())
        basicItem(ModItems.DARK_MATTER_ALCHEMY_COMPONENT.get())
        basicItem(ModItems.LIGHT_MATTER_ALCHEMY_COMPONENT.get())
        basicItem(ModItems.OSMIUM_ALCHEMY_COMPONENT.get())
        basicItem(ModItems.REFINED_OBSIDIAN_ALCHEMY_COMPONENT.get())

        basicItem(ModItems.QUARTZ_AMPLIFICATION_COMPONENT.get())
        basicItem(ModItems.ADVANCED_POWER_COMPONENT.get())
        basicItem(ModItems.FROZEN_IRON_COOLING_COMPONENT.get())
        basicItem(ModItems.FROZEN_IRON_INGOT.get())

        basicItem(ModItems.DIRTY_EMERALD.get())
        basicItem(ModItems.DIRTY_DIAMOND.get())
        basicItem(ModItems.DIRTY_RUBY.get())
        basicItem(ModItems.DIRTY_SAPPHIRE.get())
        basicItem(ModItems.DIRTY_PERIDOT.get())
        basicItem(ModItems.DIRTY_RED_GARNET.get())
        basicItem(ModItems.DIRTY_YELLOW_GARNET.get())
        basicItem(ModItems.DIRTY_APATITE.get())
        basicItem(ModItems.DIRTY_AMBER.get())
        basicItem(ModItems.DIRTY_LEPIDOLITE.get())
        basicItem(ModItems.DIRTY_MALACHITE.get())
        basicItem(ModItems.DIRTY_ONYX.get())
        basicItem(ModItems.DIRTY_MOLDAVITE.get())
        basicItem(ModItems.DIRTY_AGATE.get())
        basicItem(ModItems.DIRTY_OPAL.get())
        basicItem(ModItems.DIRTY_MORGANITE.get())
        basicItem(ModItems.DIRTY_AMETHYST.get())
        basicItem(ModItems.DIRTY_CARNELIAN.get())
        basicItem(ModItems.DIRTY_JASPER.get())
        basicItem(ModItems.DIRTY_BERYL.get())
        basicItem(ModItems.DIRTY_AQUAMARINE.get())
        basicItem(ModItems.DIRTY_GOLDEN_BERYL.get())
        basicItem(ModItems.DIRTY_HELIODOR.get())
        basicItem(ModItems.DIRTY_CITRINE.get())
        basicItem(ModItems.DIRTY_TURQUOISE.get())
        basicItem(ModItems.DIRTY_INDICOLITE.get())
        basicItem(ModItems.DIRTY_MOONSTONE.get())
        basicItem(ModItems.DIRTY_GARNET.get())
        basicItem(ModItems.DIRTY_TOPAZ.get())
        basicItem(ModItems.DIRTY_AMETRINE.get())
        basicItem(ModItems.DIRTY_TANZANITE.get())
        basicItem(ModItems.DIRTY_VIOLET_SAPPHIRE.get())
        basicItem(ModItems.DIRTY_ALEXANDRITE.get())
        basicItem(ModItems.DIRTY_BLUE_TOPAZ.get())
        basicItem(ModItems.DIRTY_SPINEL.get())
        basicItem(ModItems.DIRTY_IOLITE.get())
        basicItem(ModItems.DIRTY_BLACK_DIAMOND.get())
        basicItem(ModItems.DIRTY_CHAOS.get())
        basicItem(ModItems.DIRTY_ENDER_ESSENCE.get())
        basicItem(ModItems.DIRTY_DARK_GEM.get())
        basicItem(ModItems.DIRTY_QUARTZ.get())
        basicItem(ModItems.DIRTY_LAPIS_LAZULI.get())
        basicItem(ModItems.DIRTY_BLACK_QUARTZ.get())
        basicItem(ModItems.DIRTY_CERTUS_QUARTZ.get())

        basicItem(ModItems.CACTUS_NEEDLE.get())
        basicItem(ModItems.CACTUS_FRUIT_ON_A_NEEDLE.get())
        basicItem(ModItems.ALCHEMICAL_GOLD_NEEDLE.get())
        basicItem(ModItems.SAWDUST.get())
        basicItem(ModItems.CRUSHED_STONE.get())
        basicItem(ModItems.CRUSHED_NETHERRACK.get())

        basicItem(ModItems.RADIOACTIVE_POWDER_MIXTURE.get())

        basicItem(ModItems.IRON_ALCHEMICAL_ORE_DUST.get())
        basicItem(ModItems.GOLD_ALCHEMICAL_ORE_DUST.get())
        basicItem(ModItems.COPPER_ALCHEMICAL_ORE_DUST.get())
        basicItem(ModItems.TIN_ALCHEMICAL_ORE_DUST.get())
        basicItem(ModItems.SILVER_ALCHEMICAL_ORE_DUST.get())
        basicItem(ModItems.ZINC_ALCHEMICAL_ORE_DUST.get())
        basicItem(ModItems.NICKEL_ALCHEMICAL_ORE_DUST.get())
        basicItem(ModItems.PLATINUM_ALCHEMICAL_ORE_DUST.get())
        basicItem(ModItems.ALUMINUM_ALCHEMICAL_ORE_DUST.get())
        basicItem(ModItems.LEAD_ALCHEMICAL_ORE_DUST.get())
        basicItem(ModItems.COBALT_ALCHEMICAL_ORE_DUST.get())
        basicItem(ModItems.ARDITE_ALCHEMICAL_ORE_DUST.get())
        basicItem(ModItems.OSMIUM_ALCHEMICAL_ORE_DUST.get())
        basicItem(ModItems.DRACONIUM_ALCHEMICAL_ORE_DUST.get())
        basicItem(ModItems.TITANIUM_ALCHEMICAL_ORE_DUST.get())
        basicItem(ModItems.TUNGSTEN_ALCHEMICAL_ORE_DUST.get())
        basicItem(ModItems.CHROME_ALCHEMICAL_ORE_DUST.get())
        basicItem(ModItems.IRIDIUM_ALCHEMICAL_ORE_DUST.get())
        basicItem(ModItems.BORON_ALCHEMICAL_ORE_DUST.get())
        basicItem(ModItems.LITHIUM_ALCHEMICAL_ORE_DUST.get())
        basicItem(ModItems.MAGNESIUM_ALCHEMICAL_ORE_DUST.get())
        basicItem(ModItems.MITHRIL_ALCHEMICAL_ORE_DUST.get())
        basicItem(ModItems.YELLORIUM_ALCHEMICAL_ORE_DUST.get())
        basicItem(ModItems.URANIUM_ALCHEMICAL_ORE_DUST.get())
        basicItem(ModItems.THORIUM_ALCHEMICAL_ORE_DUST.get())

        basicItem(ModItems.PRIMUS_ALCHEMICAL_DUST.get())
        basicItem(ModItems.SECUNDUS_ALCHEMICAL_DUST.get())
        basicItem(ModItems.TERTIUS_ALCHEMICAL_DUST.get())
        basicItem(ModItems.QUARTUS_ALCHEMICAL_DUST.get())

        basicItem(ModItems.ALCHEMICAL_COAL.get())
        basicItem(ModItems.ALCHEMICAL_GOLD_INGOT.get())
        basicItem(ModItems.ALCHEMICAL_IRON_INGOT.get())
        basicItem(ModItems.ALCHEMICAL_DIAMOND.get())
        basicItem(ModItems.DARK_MATTER.get())
        basicItem(ModItems.LIGHT_MATTER.get())
        basicItem(ModItems.CRYSTAL_SHARD.get())
    }
}